"""
Static seed data for CloudGuardGraph's mock backend.

This models one coherent synthetic AWS environment matching the project
doc's canonical example chain:

    Internet -> Public EC2 -> IAM Role -> Secrets Manager -> Production DB

All IDs are stable strings so the frontend can deep-link to them. This
module is intentionally plain Python dict/list literals (not an ORM/DB) --
v1 keeps everything in memory and re-seeds on process restart. Swapping
this for the real Parser -> Detector -> Graph Builder -> ... pipeline
later means replacing `app.store` internals without touching the routers
or the frontend contract.
"""

WORKSPACE = {
    "id": "ws-prod-aws",
    "name": "Prod AWS",
    "environmentLabel": "Production",
    "provider": "aws",
}

RESOURCES = [
    {
        "id": "res-internet",
        "name": "Internet",
        "type": "internet",
        "isPublic": True,
        "tags": {},
        "findingsCount": 0,
        "worstSeverity": None,
        "connections": 2,
        "attributes": {},
    },
    {
        "id": "res-lb-public",
        "name": "lb-public-web",
        "type": "load_balancer",
        "isPublic": True,
        "tags": {"tier": "edge"},
        "findingsCount": 1,
        "worstSeverity": "medium",
        "connections": 2,
        "attributes": {"tls_policy": "ELBSecurityPolicy-2016-08 (outdated)"},
    },
    {
        "id": "res-ec2-web-01",
        "name": "ec2-web-01",
        "type": "ec2",
        "isPublic": True,
        "tags": {"role": "web", "env": "prod"},
        "findingsCount": 2,
        "worstSeverity": "critical",
        "connections": 3,
        "sourceSnippet": (
            'resource "aws_instance" "web_01" {\n'
            '  ami                    = "ami-0abcd1234"\n'
            '  instance_type          = "t3.medium"\n'
            '  vpc_security_group_ids = [aws_security_group.sg_web_open.id]\n'
            '  iam_instance_profile   = aws_iam_instance_profile.ec2_admin.name\n'
            "}"
        ),
        "attributes": {"public_ip": "54.210.88.14", "iam_role": "iam-role-ec2-admin"},
    },
    {
        "id": "res-ec2-worker-02",
        "name": "ec2-worker-02",
        "type": "ec2",
        "isPublic": True,
        "tags": {"role": "worker", "env": "prod"},
        "findingsCount": 1,
        "worstSeverity": "high",
        "connections": 2,
        "attributes": {"public_ip": "54.210.88.55", "iam_role": "iam-role-app"},
    },
    {
        "id": "res-sg-web-open",
        "name": "sg-web-open",
        "type": "security_group",
        "isPublic": True,
        "tags": {},
        "findingsCount": 1,
        "worstSeverity": "critical",
        "connections": 1,
        "sourceSnippet": (
            'resource "aws_security_group" "sg_web_open" {\n'
            '  ingress {\n'
            '    from_port   = 0\n'
            '    to_port     = 65535\n'
            '    protocol    = "tcp"\n'
            '    cidr_blocks = ["0.0.0.0/0"]\n'
            "  }\n"
            "}"
        ),
        "attributes": {"inbound": "0.0.0.0/0 : 0-65535/tcp"},
    },
    {
        "id": "res-sg-ssh-open",
        "name": "sg-ssh-open",
        "type": "security_group",
        "isPublic": True,
        "tags": {},
        "findingsCount": 1,
        "worstSeverity": "high",
        "connections": 1,
        "attributes": {"inbound": "0.0.0.0/0 : 22/tcp"},
    },
    {
        "id": "res-iam-role-ec2-admin",
        "name": "iam-role-ec2-admin",
        "type": "iam_role",
        "isPublic": False,
        "tags": {},
        "findingsCount": 3,
        "worstSeverity": "critical",
        "connections": 3,
        "sourceSnippet": (
            'resource "aws_iam_role_policy" "ec2_admin_policy" {\n'
            '  policy = jsonencode({\n'
            '    Statement = [{\n'
            '      Effect   = "Allow"\n'
            '      Action   = "*"\n'
            '      Resource = "*"\n'
            "    }]\n"
            "  })\n"
            "}"
        ),
        "attributes": {"action": "*", "resource": "*", "attached_to": "ec2-web-01"},
    },
    {
        "id": "res-iam-role-app",
        "name": "iam-role-app",
        "type": "iam_role",
        "isPublic": False,
        "tags": {},
        "findingsCount": 1,
        "worstSeverity": "high",
        "connections": 2,
        "attributes": {"action": "secretsmanager:GetSecretValue", "resource": "*"},
    },
    {
        "id": "res-s3-public-assets",
        "name": "s3-public-assets",
        "type": "s3",
        "isPublic": True,
        "tags": {},
        "findingsCount": 2,
        "worstSeverity": "medium",
        "connections": 1,
        "attributes": {"versioning": "disabled"},
    },
    {
        "id": "res-s3-private-backups",
        "name": "s3-private-backups",
        "type": "s3",
        "isPublic": False,
        "tags": {},
        "findingsCount": 1,
        "worstSeverity": "low",
        "connections": 1,
        "attributes": {"versioning": "disabled"},
    },
    {
        "id": "res-secret-db-credential",
        "name": "prod-db-credential",
        "type": "secret",
        "isPublic": False,
        "tags": {},
        "findingsCount": 1,
        "worstSeverity": "critical",
        "connections": 2,
        "attributes": {"rotation": "disabled"},
    },
    {
        "id": "res-secret-api-key",
        "name": "third-party-api-key",
        "type": "secret",
        "isPublic": False,
        "tags": {},
        "findingsCount": 1,
        "worstSeverity": "medium",
        "connections": 1,
        "attributes": {"rotation": "disabled"},
    },
    {
        "id": "res-db-production",
        "name": "db-production",
        "type": "database",
        "isPublic": False,
        "tags": {"data_classification": "restricted"},
        "findingsCount": 1,
        "worstSeverity": "high",
        "connections": 1,
        "attributes": {"engine": "postgres", "encryption": "disabled"},
    },
    {
        "id": "res-db-staging",
        "name": "db-staging",
        "type": "database",
        "isPublic": False,
        "tags": {"data_classification": "internal"},
        "findingsCount": 0,
        "worstSeverity": None,
        "connections": 0,
        "attributes": {"engine": "postgres", "encryption": "enabled"},
    },
]

FINDINGS = [
    {
        "id": "fnd-001",
        "title": "Security group allows unrestricted inbound access",
        "severity": "critical",
        "category": "exposure",
        "ruleId": "CGG-SG-001",
        "resourceId": "res-sg-web-open",
        "resourceName": "sg-web-open",
        "resourceType": "security_group",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-1"],
        "detectedInScan": 12,
        "description": "Inbound rule allows 0.0.0.0/0 on ports 0-65535/tcp, exposing every attached instance to the entire internet.",
        "configSnippet": 'ingress {\n  cidr_blocks = ["0.0.0.0/0"]\n  from_port = 0\n  to_port = 65535\n}',
    },
    {
        "id": "fnd-002",
        "title": "EC2 instance is internet-facing",
        "severity": "high",
        "category": "exposure",
        "ruleId": "CGG-EC2-004",
        "resourceId": "res-ec2-web-01",
        "resourceName": "ec2-web-01",
        "resourceType": "ec2",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-1"],
        "detectedInScan": 12,
        "description": "Instance has a public IP and is reachable via sg-web-open, forming the entry point of an attack chain.",
        "configSnippet": 'resource "aws_instance" "web_01" {\n  associate_public_ip_address = true\n}',
    },
    {
        "id": "fnd-003",
        "title": "IAM role grants wildcard action on all resources",
        "severity": "critical",
        "category": "over_permission",
        "ruleId": "CGG-IAM-010",
        "resourceId": "res-iam-role-ec2-admin",
        "resourceName": "iam-role-ec2-admin",
        "resourceType": "iam_role",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-1"],
        "detectedInScan": 12,
        "description": '`Action: "*"` on `Resource: "*"` grants full administrative control to anything that assumes this role.',
        "configSnippet": '{\n  "Effect": "Allow",\n  "Action": "*",\n  "Resource": "*"\n}',
    },
    {
        "id": "fnd-004",
        "title": "IAM role permits iam:PassRole without restriction",
        "severity": "high",
        "category": "privilege_escalation",
        "ruleId": "CGG-IAM-014",
        "resourceId": "res-iam-role-ec2-admin",
        "resourceName": "iam-role-ec2-admin",
        "resourceType": "iam_role",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-1"],
        "detectedInScan": 12,
        "description": "Unrestricted iam:PassRole allows privilege escalation by attaching this role to new resources.",
        "configSnippet": '"Action": "iam:PassRole",\n"Resource": "*"',
    },
    {
        "id": "fnd-005",
        "title": "Secret is readable by an over-permissioned role",
        "severity": "critical",
        "category": "secrets",
        "ruleId": "CGG-SEC-002",
        "resourceId": "res-secret-db-credential",
        "resourceName": "prod-db-credential",
        "resourceType": "secret",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-1"],
        "detectedInScan": 12,
        "description": "iam-role-ec2-admin can call secretsmanager:GetSecretValue on this secret, which holds the production database credential.",
        "configSnippet": '"Action": "secretsmanager:GetSecretValue",\n"Resource": "*"',
    },
    {
        "id": "fnd-006",
        "title": "Database encryption at rest is disabled",
        "severity": "high",
        "category": "data_exposure",
        "ruleId": "CGG-DB-003",
        "resourceId": "res-db-production",
        "resourceName": "db-production",
        "resourceType": "database",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-1"],
        "detectedInScan": 12,
        "description": "storage_encrypted is false on a database tagged as restricted data classification.",
        "configSnippet": 'resource "aws_db_instance" "production" {\n  storage_encrypted = false\n}',
    },
    {
        "id": "fnd-007",
        "title": "Security group allows unrestricted SSH",
        "severity": "high",
        "category": "exposure",
        "ruleId": "CGG-SG-002",
        "resourceId": "res-sg-ssh-open",
        "resourceName": "sg-ssh-open",
        "resourceType": "security_group",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-3"],
        "detectedInScan": 12,
        "description": "Port 22 is open to 0.0.0.0/0, allowing SSH brute-force attempts from anywhere.",
        "configSnippet": 'ingress {\n  cidr_blocks = ["0.0.0.0/0"]\n  from_port = 22\n  to_port = 22\n}',
    },
    {
        "id": "fnd-008",
        "title": "S3 bucket policy allows public read access",
        "severity": "medium",
        "category": "data_exposure",
        "ruleId": "CGG-S3-005",
        "resourceId": "res-s3-public-assets",
        "resourceName": "s3-public-assets",
        "resourceType": "s3",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-2"],
        "detectedInScan": 12,
        "description": "Bucket policy grants s3:GetObject to Principal \"*\".",
        "configSnippet": '"Principal": "*",\n"Action": "s3:GetObject"',
    },
    {
        "id": "fnd-009",
        "title": "S3 bucket versioning disabled",
        "severity": "low",
        "category": "data_exposure",
        "ruleId": "CGG-S3-009",
        "resourceId": "res-s3-public-assets",
        "resourceName": "s3-public-assets",
        "resourceType": "s3",
        "status": "open",
        "partOfAttackPath": False,
        "attackPathIds": [],
        "detectedInScan": 12,
        "description": "Versioning is disabled, so accidental or malicious overwrites cannot be recovered.",
        "configSnippet": 'versioning {\n  enabled = false\n}',
    },
    {
        "id": "fnd-010",
        "title": "IAM role permits reading secrets manager on all resources",
        "severity": "high",
        "category": "over_permission",
        "ruleId": "CGG-IAM-011",
        "resourceId": "res-iam-role-app",
        "resourceName": "iam-role-app",
        "resourceType": "iam_role",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-3"],
        "detectedInScan": 12,
        "description": '"Action": "secretsmanager:GetSecretValue" scoped to "Resource": "*" instead of the one secret this workload needs.',
        "configSnippet": '"Action": "secretsmanager:GetSecretValue",\n"Resource": "*"',
    },
    {
        "id": "fnd-011",
        "title": "Secret has automatic rotation disabled",
        "severity": "medium",
        "category": "secrets",
        "ruleId": "CGG-SEC-006",
        "resourceId": "res-secret-api-key",
        "resourceName": "third-party-api-key",
        "resourceType": "secret",
        "status": "open",
        "partOfAttackPath": True,
        "attackPathIds": ["path-3"],
        "detectedInScan": 12,
        "description": "No rotation schedule is configured; a leaked key remains valid indefinitely.",
        "configSnippet": 'resource "aws_secretsmanager_secret_rotation" "api_key" {\n  # not configured\n}',
    },
    {
        "id": "fnd-012",
        "title": "Load balancer uses an outdated TLS policy",
        "severity": "medium",
        "category": "exposure",
        "ruleId": "CGG-ELB-002",
        "resourceId": "res-lb-public",
        "resourceName": "lb-public-web",
        "resourceType": "load_balancer",
        "status": "open",
        "partOfAttackPath": False,
        "attackPathIds": [],
        "detectedInScan": 12,
        "description": "ELBSecurityPolicy-2016-08 permits deprecated TLS 1.0/1.1 ciphers.",
        "configSnippet": 'ssl_policy = "ELBSecurityPolicy-2016-08"',
    },
    {
        "id": "fnd-013",
        "title": "S3 bucket versioning disabled",
        "severity": "low",
        "category": "data_exposure",
        "ruleId": "CGG-S3-009",
        "resourceId": "res-s3-private-backups",
        "resourceName": "s3-private-backups",
        "resourceType": "s3",
        "status": "open",
        "partOfAttackPath": False,
        "attackPathIds": [],
        "detectedInScan": 12,
        "description": "Versioning is disabled on a backup bucket, undermining its purpose as a recovery source.",
        "configSnippet": 'versioning {\n  enabled = false\n}',
    },
    {
        "id": "fnd-014",
        "title": "IAM access key rotation exceeds 90 days",
        "severity": "low",
        "category": "over_permission",
        "ruleId": "CGG-IAM-020",
        "resourceId": "res-iam-role-app",
        "resourceName": "iam-role-app",
        "resourceType": "iam_role",
        "status": "suppressed",
        "partOfAttackPath": False,
        "attackPathIds": [],
        "detectedInScan": 11,
        "description": "Attached access key has not been rotated in over 90 days.",
        "configSnippet": "# access key metadata (rotation age: 132 days)",
        "suppressReason": "Service account key rotation scheduled with next maintenance window.",
        "suppressExpiry": "2026-10-01",
    },
    {
        "id": "fnd-015",
        "title": "Security group permits all outbound traffic",
        "severity": "low",
        "category": "exposure",
        "ruleId": "CGG-SG-007",
        "resourceId": "res-sg-web-open",
        "resourceName": "sg-web-open",
        "resourceType": "security_group",
        "status": "open",
        "partOfAttackPath": False,
        "attackPathIds": [],
        "detectedInScan": 12,
        "description": "Unrestricted egress simplifies data exfiltration if the instance is ever compromised.",
        "configSnippet": 'egress {\n  cidr_blocks = ["0.0.0.0/0"]\n}',
    },
]

ATTACK_PATHS = [
    {
        "id": "path-1",
        "targetAssetId": "res-db-production",
        "targetAssetName": "db-production",
        "entryPoint": "internet",
        "riskScore": 94,
        "severity": "critical",
        "hops": 4,
        "status": "new",
        "nodes": [
            {"resourceId": "res-internet", "resourceName": "Internet", "resourceType": "internet"},
            {"resourceId": "res-ec2-web-01", "resourceName": "ec2-web-01", "resourceType": "ec2"},
            {"resourceId": "res-iam-role-ec2-admin", "resourceName": "iam-role-ec2-admin", "resourceType": "iam_role"},
            {"resourceId": "res-secret-db-credential", "resourceName": "prod-db-credential", "resourceType": "secret"},
            {"resourceId": "res-db-production", "resourceName": "db-production", "resourceType": "database"},
        ],
        "contributingFindingIds": ["fnd-001", "fnd-002", "fnd-003", "fnd-004", "fnd-005", "fnd-006"],
        "explanation": [
            "ec2-web-01 is reachable from the internet because sg-web-open allows inbound traffic from 0.0.0.0/0 on all ports.",
            "ec2-web-01 assumes iam-role-ec2-admin, which grants \"Action\": \"*\" on \"Resource\": \"*\" — effectively administrative access.",
            "That role can call secretsmanager:GetSecretValue on prod-db-credential, the production database's own credential.",
            "db-production stores restricted-classification customer and financial data, and its own encryption at rest is disabled.",
        ],
        "recommendationId": "rec-001",
    },
    {
        "id": "path-2",
        "targetAssetId": "res-s3-public-assets",
        "targetAssetName": "s3-public-assets",
        "entryPoint": "internet",
        "riskScore": 61,
        "severity": "high",
        "hops": 3,
        "status": "existing",
        "nodes": [
            {"resourceId": "res-internet", "resourceName": "Internet", "resourceType": "internet"},
            {"resourceId": "res-ec2-web-01", "resourceName": "ec2-web-01", "resourceType": "ec2"},
            {"resourceId": "res-s3-public-assets", "resourceName": "s3-public-assets", "resourceType": "s3"},
        ],
        "contributingFindingIds": ["fnd-001", "fnd-002", "fnd-008"],
        "explanation": [
            "ec2-web-01 is internet-facing via the same open security group used in path-1.",
            "The instance's role and the bucket policy both permit reading s3-public-assets, and the bucket policy separately allows public read access to Principal \"*\".",
            "Any object placed in this bucket — including ones an attacker uploads through the compromised instance — becomes world-readable.",
        ],
        "recommendationId": "rec-003",
    },
    {
        "id": "path-3",
        "targetAssetId": "res-secret-api-key",
        "targetAssetName": "third-party-api-key",
        "entryPoint": "internet",
        "riskScore": 48,
        "severity": "medium",
        "hops": 3,
        "status": "new",
        "nodes": [
            {"resourceId": "res-internet", "resourceName": "Internet", "resourceType": "internet"},
            {"resourceId": "res-ec2-worker-02", "resourceName": "ec2-worker-02", "resourceType": "ec2"},
            {"resourceId": "res-secret-api-key", "resourceName": "third-party-api-key", "resourceType": "secret"},
        ],
        "contributingFindingIds": ["fnd-007", "fnd-010", "fnd-011"],
        "explanation": [
            "ec2-worker-02 allows unrestricted SSH (0.0.0.0/0 on port 22) via sg-ssh-open, making credential brute-forcing feasible.",
            "The instance assumes iam-role-app, which can read any secret in the account rather than just the one it needs.",
            "third-party-api-key has no rotation schedule, so a stolen key remains valid indefinitely.",
        ],
        "recommendationId": "rec-004",
    },
]

RECOMMENDATIONS = [
    {
        "id": "rec-001",
        "findingId": "fnd-003",
        "attackPathId": "path-1",
        "title": "Replace wildcard IAM policy with least-privilege statements",
        "summary": "iam-role-ec2-admin grants full administrative access. Scope it to only the actions ec2-web-01 actually needs, and drop iam:PassRole entirely unless a specific downstream role requires it.",
        "resourceName": "iam-role-ec2-admin",
        "estRiskReduction": 57,
        "effort": "medium",
        "status": "suggested",
        "diffBefore": '{\n  "Effect": "Allow",\n  "Action": "*",\n  "Resource": "*"\n}',
        "diffAfter": '{\n  "Effect": "Allow",\n  "Action": [\n    "secretsmanager:GetSecretValue"\n  ],\n  "Resource": "arn:aws:secretsmanager:*:*:secret:app/*"\n}',
        "modelAttribution": "Generated by local model (Llama 3 via Ollama)",
    },
    {
        "id": "rec-002",
        "findingId": "fnd-001",
        "attackPathId": "path-1",
        "title": "Restrict the web security group to known ranges",
        "summary": "sg-web-open allows 0.0.0.0/0 on every port. Limit inbound rules to 80/443 from the load balancer's security group only.",
        "resourceName": "sg-web-open",
        "estRiskReduction": 22,
        "effort": "low",
        "status": "suggested",
        "diffBefore": 'ingress {\n  from_port   = 0\n  to_port     = 65535\n  protocol    = "tcp"\n  cidr_blocks = ["0.0.0.0/0"]\n}',
        "diffAfter": 'ingress {\n  from_port       = 443\n  to_port         = 443\n  protocol        = "tcp"\n  security_groups = [aws_security_group.lb_public.id]\n}',
        "modelAttribution": "Generated by local model (Llama 3 via Ollama)",
    },
    {
        "id": "rec-003",
        "findingId": "fnd-008",
        "attackPathId": "path-2",
        "title": "Enable S3 Block Public Access",
        "summary": "s3-public-assets has a bucket policy granting public read. Enable account-level Block Public Access and scope reads to a CloudFront origin access identity instead.",
        "resourceName": "s3-public-assets",
        "estRiskReduction": 18,
        "effort": "low",
        "status": "suggested",
        "diffBefore": '"Principal": "*",\n"Action": "s3:GetObject"',
        "diffAfter": '"Principal": {\n  "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity"\n},\n"Action": "s3:GetObject"',
        "modelAttribution": "Generated by local model (Qwen via Ollama)",
    },
    {
        "id": "rec-004",
        "findingId": "fnd-010",
        "attackPathId": "path-3",
        "title": "Scope secrets access to the specific secret ARN",
        "summary": "iam-role-app can read every secret in the account. Restrict the policy's Resource to only third-party-api-key's ARN.",
        "resourceName": "iam-role-app",
        "estRiskReduction": 16,
        "effort": "low",
        "status": "suggested",
        "diffBefore": '"Action": "secretsmanager:GetSecretValue",\n"Resource": "*"',
        "diffAfter": '"Action": "secretsmanager:GetSecretValue",\n"Resource": "arn:aws:secretsmanager:*:*:secret:third-party-api-key-*"',
        "modelAttribution": "Generated by local model (Gemma via Ollama)",
    },
    {
        "id": "rec-005",
        "findingId": "fnd-006",
        "attackPathId": "path-1",
        "title": "Enable encryption at rest for the production database",
        "summary": "db-production has storage_encrypted set to false despite holding restricted-classification data.",
        "resourceName": "db-production",
        "estRiskReduction": 11,
        "effort": "low",
        "status": "suggested",
        "diffBefore": 'resource "aws_db_instance" "production" {\n  storage_encrypted = false\n}',
        "diffAfter": 'resource "aws_db_instance" "production" {\n  storage_encrypted = true\n  kms_key_id        = aws_kms_key.rds.arn\n}',
        "modelAttribution": "Generated by local model (Llama 3 via Ollama)",
    },
]

RISK_ANALYSIS = {
    "compositeScore": 91,
    "factors": {
        "exposure": 88,
        "privilegeLevel": 93,
        "dataSensitivity": 90,
        "exploitability": 82,
        "dangerousPermissions": 95,
    },
    "distribution": [
        {"bucket": "0-20", "count": 0},
        {"bucket": "21-40", "count": 0},
        {"bucket": "41-60", "count": 1},
        {"bucket": "61-80", "count": 1},
        {"bucket": "81-100", "count": 1},
    ],
    "byAsset": [
        {"resourceId": "res-db-production", "resourceName": "db-production", "resourceType": "database", "contribution": 94},
        {"resourceId": "res-s3-public-assets", "resourceName": "s3-public-assets", "resourceType": "s3", "contribution": 61},
        {"resourceId": "res-secret-api-key", "resourceName": "third-party-api-key", "resourceType": "secret", "contribution": 48},
        {"resourceId": "res-iam-role-ec2-admin", "resourceName": "iam-role-ec2-admin", "resourceType": "iam_role", "contribution": 44},
    ],
}

RISK_TREND = [
    {"scanNumber": 7, "date": "2026-06-11", "riskScore": 79, "criticalPaths": 1},
    {"scanNumber": 8, "date": "2026-06-18", "riskScore": 84, "criticalPaths": 2},
    {"scanNumber": 9, "date": "2026-06-25", "riskScore": 92, "criticalPaths": 3},
    {"scanNumber": 10, "date": "2026-07-02", "riskScore": 85, "criticalPaths": 2},
    {"scanNumber": 11, "date": "2026-07-16", "riskScore": 87, "criticalPaths": 2},
    {"scanNumber": 12, "date": "2026-07-23", "riskScore": 91, "criticalPaths": 3},
]

SCANS = [
    {
        "id": "scan-7", "number": 7, "workspaceId": "ws-prod-aws", "status": "success",
        "triggeredBy": "Alex Romero", "triggeredAt": "2026-06-11T09:12:00Z", "finishedAt": "2026-06-11T09:14:02Z",
        "riskScore": 79, "riskDelta": 0, "criticalPathCount": 1, "criticalPathDelta": 0,
        "findingsCount": 18, "assetsCount": 12,
    },
    {
        "id": "scan-8", "number": 8, "workspaceId": "ws-prod-aws", "status": "success",
        "triggeredBy": "Jordan Lee", "triggeredAt": "2026-06-18T14:03:00Z", "finishedAt": "2026-06-18T14:05:41Z",
        "riskScore": 84, "riskDelta": 5, "criticalPathCount": 2, "criticalPathDelta": 1,
        "findingsCount": 20, "assetsCount": 12,
    },
    {
        "id": "scan-9", "number": 9, "workspaceId": "ws-prod-aws", "status": "success",
        "triggeredBy": "Alex Romero", "triggeredAt": "2026-06-25T10:47:00Z", "finishedAt": "2026-06-25T10:49:12Z",
        "riskScore": 92, "riskDelta": 8, "criticalPathCount": 3, "criticalPathDelta": 1,
        "findingsCount": 23, "assetsCount": 13,
    },
    {
        "id": "scan-10", "number": 10, "workspaceId": "ws-prod-aws", "status": "success",
        "triggeredBy": "Jordan Lee", "triggeredAt": "2026-07-02T08:30:00Z", "finishedAt": "2026-07-02T08:32:55Z",
        "riskScore": 85, "riskDelta": -7, "criticalPathCount": 2, "criticalPathDelta": -1,
        "findingsCount": 21, "assetsCount": 13,
    },
    {
        "id": "scan-11", "number": 11, "workspaceId": "ws-prod-aws", "status": "success",
        "triggeredBy": "Priya Nair", "triggeredAt": "2026-07-16T16:20:00Z", "finishedAt": "2026-07-16T16:22:31Z",
        "riskScore": 87, "riskDelta": 2, "criticalPathCount": 2, "criticalPathDelta": 0,
        "findingsCount": 22, "assetsCount": 13,
    },
    {
        "id": "scan-12", "number": 12, "workspaceId": "ws-prod-aws", "status": "success",
        "triggeredBy": "Alex Romero", "triggeredAt": "2026-07-23T07:58:00Z", "finishedAt": "2026-07-23T08:00:47Z",
        "riskScore": 91, "riskDelta": 4, "criticalPathCount": 3, "criticalPathDelta": 1,
        "findingsCount": 25, "assetsCount": 13,
    },
]

PIPELINE_STAGES = [
    "parser",
    "detector",
    "graph_builder",
    "attack_path_engine",
    "risk_engine",
    "explainability",
    "ai_remediation",
    "simulation_preview",
]

ACTIVITY_EVENTS = [
    {
        "id": "evt-001", "type": "scan_completed",
        "message": "Scan #12 completed — risk score 91 (+4)",
        "timestamp": "2026-07-23T08:00:47Z", "read": False, "href": "/scans",
    },
    {
        "id": "evt-002", "type": "new_critical_path",
        "message": "New critical attack path detected: Internet → ec2-web-01 → db-production",
        "timestamp": "2026-07-23T08:00:50Z", "read": False, "href": "/attack-paths/path-1",
    },
    {
        "id": "evt-003", "type": "recommendation_ready",
        "message": "5 AI recommendations generated for Scan #12",
        "timestamp": "2026-07-23T08:01:10Z", "read": False, "href": "/recommendations",
    },
    {
        "id": "evt-004", "type": "report_generated",
        "message": "Executive Summary report generated for Scan #11",
        "timestamp": "2026-07-16T16:30:00Z", "read": True, "href": "/reports",
    },
    {
        "id": "evt-005", "type": "scan_completed",
        "message": "Scan #11 completed — risk score 87 (+2)",
        "timestamp": "2026-07-16T16:22:31Z", "read": True, "href": "/scans",
    },
    {
        "id": "evt-006", "type": "user_role_changed",
        "message": "Sam Whitfield invited as Viewer",
        "timestamp": "2026-07-15T11:02:00Z", "read": True, "href": "/users",
    },
]

USERS = [
    {"id": "usr-1", "name": "Priya Nair", "email": "priya.nair@cloudguardgraph.io", "role": "admin", "status": "active", "lastActive": "2026-07-23T08:05:00Z"},
    {"id": "usr-2", "name": "Alex Romero", "email": "alex.romero@cloudguardgraph.io", "role": "analyst", "status": "active", "lastActive": "2026-07-23T07:55:00Z"},
    {"id": "usr-3", "name": "Jordan Lee", "email": "jordan.lee@cloudguardgraph.io", "role": "contributor", "status": "active", "lastActive": "2026-07-22T18:40:00Z"},
    {"id": "usr-4", "name": "Sam Whitfield", "email": "sam.whitfield@partner-co.com", "role": "viewer", "status": "invited"},
    {"id": "usr-5", "name": "Dana Cole", "email": "dana.cole@auditfirm.com", "role": "auditor", "status": "active", "lastActive": "2026-07-10T09:00:00Z"},
]

AUDIT_LOGS = [
    {"id": "log-1", "timestamp": "2026-07-23T08:01:15Z", "actor": "Alex Romero", "action": "scan.triggered", "target": "Scan #12", "detail": "Uploaded terraform-prod-bundle.zip"},
    {"id": "log-2", "timestamp": "2026-07-22T15:12:00Z", "actor": "Jordan Lee", "action": "finding.suppressed", "target": "fnd-014", "detail": "Justification: rotation scheduled with next maintenance window"},
    {"id": "log-3", "timestamp": "2026-07-16T16:30:05Z", "actor": "Priya Nair", "action": "report.generated", "target": "Executive Summary — Scan #11"},
    {"id": "log-4", "timestamp": "2026-07-15T11:02:00Z", "actor": "Priya Nair", "action": "user.invited", "target": "sam.whitfield@partner-co.com", "detail": "Role: Viewer"},
    {"id": "log-5", "timestamp": "2026-07-10T09:31:00Z", "actor": "Dana Cole", "action": "report.downloaded", "target": "Full Technical Assessment — Scan #9"},
    {"id": "log-6", "timestamp": "2026-07-02T08:33:10Z", "actor": "Jordan Lee", "action": "settings.updated", "target": "Scan Rules", "detail": "Enabled category: secrets"},
]

REPORTS = [
    {"id": "rpt-1", "name": "Executive Summary — Scan #11", "template": "executive_summary", "scanNumber": 11, "generatedAt": "2026-07-16T16:30:00Z", "status": "ready"},
    {"id": "rpt-2", "name": "Full Technical Assessment — Scan #9", "template": "full_technical", "scanNumber": 9, "generatedAt": "2026-06-25T11:00:00Z", "status": "ready"},
]
